# Generated by Django 6.0.4 on 2026-05-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingjob',
            name='source_video_filename',
            field=models.CharField(blank=True, default='', help_text='스테이징 input/ 동영상 파일명 (공개 검색 URL용)', max_length=255),
        ),
        migrations.AlterField(
            model_name='embeddingjob',
            name='canonical_key',
            field=models.CharField(db_index=True, editable=False, help_text='Qdrant·S3 논리 키: `{slug}/episodes/{n}/frames` (JPG는 스테이징에만 저장)', max_length=512),
        ),
    ]
