# Generated by Django 6.0.4 on 2026-05-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineTrace',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('search', '검색'), ('indexing', '색인')], db_index=True, max_length=16)),
                ('job_public_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ok', '성공'), ('error', '오류'), ('empty', '결과 없음')], db_index=True, max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_traces', to='discovery.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
